### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by natec425** [BaseCampCoding/fundamentals-of-programming-pt-1-unit-project-joseph-and-bryce#1]
Hey @Bryce-Taylor and @JosephDandan5010,

Your proposal looks good with the exception that you are missing your daily goals section. I think you will be good to go once you finish that.

**Comment by JosephDandan5010** [comment]
Thanks for the feedback!

**Comment by natec425** [comment]
Looks good to me. I think y'all are good to go.

**Comment by JosephDandan5010** [comment]
Alright, thanks!

**Comment by JosephDandan5010** [comment]
Our plan for today is to first greet the user on what our program is with
simple instructions and definitions of nouns, verbs, adjectives, and
adverbs. Second, we will make the first story and make sure it works with
proper user input and string concatenation.
